table dim_product
	lineageTag: f7dcdbc1-66c0-5330-83a4-98cb7a373bb1

	column product
		dataType: string
		lineageTag: 20154186-aacc-512d-a2ea-f08971c6e13d
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 34d05fb6-390d-5ac4-861d-7d0a4e07c585
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
					Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZA9T4RAEIb/yoT6KLSxFjhDIqfFqleQK4ZlDia37Gz2I/H+vYs0JlI/79dM3xePTyVbPcNJLEfxxaFoODiD91BcDn1RmURRJM6gHOGNVsFzGll+aSP6xnYCFTGy2JVpTSGIZ9r8Rz+JlYU11DPy6n5JPjclTxv/juQtGlCqgYePKgtUnoHThjt0Udyab8ed9BPpGS3r7H+l+yDo91RvwoHKGq0mY9a5LeHoZrGZ/71GLegjdMcGOlxcRq0sBO/XK+ttzaeqyhpqHAzt1Jxp0LhA22T2xSNtoWf2ZLIuPziFf7bLDw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [product = _t, category = _t]),
					Typed = Table.TransformColumnTypes(Source, {{"product", type text}, {"category", type text}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
