table dim_date
	lineageTag: b0ce914a-c8cc-5cd6-a349-3daad3294967
	dataCategory: Time

	column Date
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: be1b96c6-950f-576b-a83f-fe50caa2efa6
		summarizeBy: none
		isKey
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9a2ec259-7437-5ff0-9422-25b7182a5592
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 42354949-1080-5be4-be4d-fa42650c4703
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: d6465c54-d2c7-5514-8757-0aac95b6fcc3
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: bcb3eb02-dfd4-5dc7-b68e-2b25054bf58d
		summarizeBy: none
		sortByColumn: MonthNumber
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: d5011b81-a5cc-5705-83a1-553d0999c76e
		summarizeBy: none
		sortByColumn: MonthStart
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column MonthStart
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 47337db6-3014-5bdc-b2c9-362d5fd8195b
		summarizeBy: none
		sourceColumn: MonthStart

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column WeekdayNumber
		dataType: int64
		formatString: 0
		lineageTag: 7775754e-3837-5f1a-b728-747e00557c1e
		summarizeBy: none
		sourceColumn: WeekdayNumber

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: b9db864f-242b-59af-9f39-e0eb19ee355e
		summarizeBy: none
		sortByColumn: WeekdayNumber
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		lineageTag: 9fd458d0-cc28-57e0-86ed-4edf8567078a
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
					Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rdaxahtBFIXhVwmuE9h77szsTJnGhcFFiCGFcaEQQwLBCUpc5O2jtVxkczUaCf3gHcmW+JHWX3Hu7680qbybbPdz9fbll93Dh+X5ct1snvbnm9dXVu9Ou+vu6/PuvN58//V49fD2n5zOzuUltP12OOdn55Y/fNz8Xj7j9vm/Wjq7Ni+156eDtXx2bblufzwd/qrl7Nxyr+92n+pgbj47t9zrT49fDucqy6ShTGwimZiRTEwoE3OUiSWUiWWUiRWWyYwyqSiThjLRhDKRoUwklIkcZaJEMlEmmaiwTGaWSWWZNJSJTygTN46J4g5b7vP14+f9ua5pwERxho1rfSaKM2yc6zNR3GHjXJ+J4hAb5/pMFIfYONdnojjExrljTCrKpKFMwgy7jIkZysSEMjFHmVgimVgmmVhhmcwsk8oyaSgTTSgTGclEIpnIUSZKKBNllIkKy2RmmVSOicdtstyY2812f65rPmDicZuMa30mHrfJONdn4nGbjHN9Jh63yTjXZ+Jxm4xzfSYet8k4d4xJRZk0lEnYJpcxMUOZmFAm5igTSyQTyyQTKyyTmWVSWSYNZaIJZSIjmUgkEznKRAlloowyUWGZzCyTijJpJBOfUCZuIJO03mF6/a+9/7ndn+tcGjFJ6yF2Wq7PJK2H2Gm5PpO0HmKn5bpM0nqHnVbrMknrGXZarc8krWfYabmjTCrLpKFMVkPsciZmJBMTycQcZWIJZWIZZWKFZTKzTCrKpJFMNKFMZCgTCWUiR5kooUyUSSYqKJOZZVJZJg1l4hPIJMfllF8m2J/9uc7lEZMcl9M412WS43Aa17pMctxN41qfSY7DaZzrM8lxOY1zfSY5Lqdx7iiTyjJpJJMwnC5iYoYyMaFMzFEmllAmllEmVlAmM8qkskwaykQTykSGMpFQJnKSiRLJRBllosIymVkmlWXSUCY+kUzcOCYlzrDlyc3Le3fnulZGTEqcYeNcn0mJO2yc6zMpcYiNc30mJQ6xca7PpMQhNs51mZS4w8a1Y0wqy6ShTMIOu4yJGcrEhDIxJ5lYIplYRplYYZnMLJPKMmkoE00kExnJREKZyFEmSigTZZSJCstkRplUlElDmfh0OZOHvw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Year = _t, Quarter = _t, MonthNumber = _t, Month = _t, MonthYear = _t, MonthStart = _t, WeekdayNumber = _t, Weekday = _t, IsWeekend = _t]),
					Typed = Table.TransformColumnTypes(Source, {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNumber", Int64.Type}, {"Month", type text}, {"MonthYear", type text}, {"MonthStart", type date}, {"WeekdayNumber", Int64.Type}, {"Weekday", type text}, {"IsWeekend", type logical}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
