table fact_sales
	lineageTag: 0d7b295c-62ba-5241-8a34-30dff427c1d9

	column order_id
		dataType: string
		lineageTag: 9e896684-1cd1-5c98-a589-7d5f008d9f3c
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9108c18-041f-561e-8418-74d1284821df
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column customer
		dataType: string
		lineageTag: 129fcf4b-5abd-5a68-b2b1-ff1d38de8330
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: cb7527c6-b723-58d6-8313-f4ca5620aac2
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 7d6a1345-bd53-5e90-9bbe-0ac7b9d75525
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: c093d01d-8248-50a3-81bc-457704e897f8
		summarizeBy: none
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 95174bcd-cd23-5f60-9972-5515bf0c1728
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: 0%
		lineageTag: 54378cdb-afc8-5b77-8779-b2a1690a6c3e
		summarizeBy: none
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 38986b2f-9851-57bf-a4ae-4fbd3539d5a9
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "fact_sales.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"order_id", type text}, {"order_date", type date}, {"customer", type text}, {"product", type text}, {"channel", type text}, {"quantity", Int64.Type}, {"unit_price", Currency.Type}, {"discount", type number}, {"revenue", Currency.Type}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
