table fact_sales
	lineageTag: 0d7b295c-62ba-5241-8a34-30dff427c1d9

	column order_id
		dataType: string
		lineageTag: 9e896684-1cd1-5c98-a589-7d5f008d9f3c
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9108c18-041f-561e-8418-74d1284821df
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column customer
		dataType: string
		lineageTag: 129fcf4b-5abd-5a68-b2b1-ff1d38de8330
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: cb7527c6-b723-58d6-8313-f4ca5620aac2
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 7d6a1345-bd53-5e90-9bbe-0ac7b9d75525
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: c093d01d-8248-50a3-81bc-457704e897f8
		summarizeBy: none
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 95174bcd-cd23-5f60-9972-5515bf0c1728
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: 0%
		lineageTag: 54378cdb-afc8-5b77-8779-b2a1690a6c3e
		summarizeBy: none
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 38986b2f-9851-57bf-a4ae-4fbd3539d5a9
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
					Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pb1tzyU3ciX4VwR/nr7L95eP7m4vPBi3ZzEaw8AO5sPjdu2o0KWqXkmeXe+vnySTZJwI5k0yawEJqhQKkXmZzGC8nDjnv/23v/nxf4vW5L/5D39jlAm/U/r457j448fXz5++/PDPn7/8+u3rcf13/+9vn375+vHlhx9//OMP+r/+/vhf//Hr73787dsvn44/uuPfHF4mHf9VL+WP/9jgXyn8zX//D+cdvJJ3+Lvffvr4+sPvf/n2/1T7v/yPb1+//fz5zz/84aePz79w8+WvG29ezlX7utg32r18rPb/2SujnLT/n798/p+fP374/b/99ttx9adPfz5u9/nPxy/4T5/+/V++ffzyr+XvfP3y+Wu/Q0ovFc8fMK66+Tgt0N9++fzDf/n4/z6OP/7zp3/588fPP/z9H6VFn1/KDIvnVbNo/WTx7z9+/fVYkT99fPn8l2L18y+fvnz69dcf/vTt3379hKbrTz1+vR+mc3qR5Wyl5T/89OXbp/60F2+SPbRW+pUyLXQKr6C7cRendf7Tx79//PDjT58+/+Wn4+ofv33+9dPv/vDx9c+fvhxG/8cPf//p41//+tO3r59+xRuVVdHOv+z4CSar17ld/vF3WhuPtzFju/zp27kjTPzd569//um4/vr52CQX20X7lwbr52UzL3ZLMf+3//7p158+xhrd7UZTd2Pb5u3VqmOxhnUdpPX2av/j//0vH1+Oy3/68fe/+8MPf/j4ly+f5ifX5pXTsHxeta9I6em52y7/+387bvD562pl6qObw6Sl92tjglsYn+aH//r146cf/uvHv3+p9qaNKZfevYyBD1W9jr3e9o+qFpn5H7/9X8cP+MOXj1/+8uly6dnuNC6eZtt7PS+bdV2/X2a9+bE/fvzPz2UD/vHbn/9SduWPv3389rk6Nr4lTXx5jU4mvOLwAjZNu/Ifvx0r8398/Pbpy+XS80cv71LDlqyX46tV0jb7an//5d8+/fbt228//fDjXz99/OXTZD2pl43kfmN42bEuzsc3L/U/HR/Vpnc8VsKRd6xXfcPXJRvmy976p69/+Xo69h9//vjltx/+4e/++MM/fPz814vtmF/eMR+Zut3jCJF222f6p89fvtQluHc34lbaHfeCI8ok19xm+bZSkDf7u59//hjf7NULEPZjfpG31z693Dj+3LRC//D5ODLGN7Ww3l6wz+wF+0C7x0n752f1zx9fTmPTa2D7vrwE9g7GK4hsVRy8gnZM3QcG+jyccjtPys84rOdhPilpvh4nwxts7J5o8cndCDk0dzWuv9Cxd643vbhB1q8ALzXZlxlv9ThHpjvUU+oiLhBrEg57jl6mj+WybxaV3q15f/T1ouvjRDL0Tttl95PWyzv8nx+/fLw5n3h0cCxAoAc/fNjYhDpraXU6nS5DJddeHRzXNr6i6bvk8F9o2Pc3OTb37NXlalj90uRl2mU3z72jp+fujn0dDhyeRdOh7Y4tb0cwo8Jk/3TtLTR9Gw2Yc70VLUugL1MlLa3Ww+i/fPv118973+UI2M847wj7yKXHJK3XHdLD9YW/8qe/0nTauWMDetqAPB3wtMXHl/8+/D0X/BVhuZunrYmAvV7sxR5sX6Gjb92k+BrH83FUSLOng+1bZHGCmpZR0BaM/V2W81nl64fuYcvCuj/9aooQ1R2vM1MAYKf1/qdffy6equ2W2/CirGiMrxzg+7SvNM5prZn10LKjkTvehqSuhaTGQup1nBjj6zfcWXXrPRPYOzkTJHb1qh9AVkvj7CvaOiOOpQ/gXEoYQDFMMvIGLSTtn9J2CONaCBMxXErltfQQxk73+s/H+TmOo3Xc7uEVux5flCNJW2m5BZDNh93Zbt+rAmeQeiZcbNvJ9vlpjdLAxmF3nNIBDrt6OXzNtH/OU3oEX5s5q63rHyHGc07T8WdMmu5TTqm2+k8S4yO5jPAtG38E85Qp+HS9XuP3LLyFPcOaFgn3pMpAmpOvF6z7urWzCOX0Jmdx3CWQrwvSeg2Fe+yxl4rYgKmIJet5+gRuUhGenuVeUdHnUUvfFXfPsXugFgFvxKiBRdeWkm0vDZ8rPU7BvXM2QeihHByGJkr75yl+frSbW9K3fQ93iRaOXMfD4DjcTvOhi2gSojIqYrkwLTm9xzcGWzyayM8EV6LUEUWyrZH6YvTXuC6c6FHOK7c4cq6eC5RTKihpXQbtd/ukfDVWsZKeLrumnyI8w05sOf7h46+/fftrCX6/XhxO1r2sGw8ddFmfUcwL0morVI2je3OL6Oa12md5vlr/soZ2Olv8TLf6259+/vSvi9Vpn6dzUC0sV2OzTMbZIX7rr9onFPATspS5a1YqrIHOGTl1Z7iRe5iXg4LeednrYTZJ89Ubvt+UoqTkX8mxKmcay6KNlbbrd9m+/ttVcWfIB4eq1apEOd2zZC9t1yVv9aS3FfEj77VQG/Qazh3HPiF63r5DlrW70Gt31Y63UG53MU62zxxvnJr3bgo6A+dV+zIdS9a1nuO795+nPj9PaBGcV6PaG6VpFlY/q31581KZbnQcE3oUfXmIpPUcIt1mwLZlwMmSn4mulPX618/q1np0Dfo39PCXqBf2gbwvH2//nvy0Zs3P3Ef0bCedrhdrPpaCr+mX1D36fbFkeOnMzpNITYTA9lV5rP/92PY/f2w2EeyowZerIxcc74J1cDTUyEflYNmKc757hlbhT3Cq8GxQjyp5/4wfdYhSKeiR0w89L6w9OS/vw4vaN/7iDBXSy9Ma+ZjKQdnfs5l+RCuovk9q2cstwUKG6oo/PB/k4ywrxLe73wcx4x3U2x1PP7osXk/v+Dy0dqz3epZyrJ6lqEXECqs1M2SB1EYr1/fa5OiyUBZrWFRSzdf9M1Z+pxKf2DFzpPm93ldukK6ff3zDq0CtFJ3JPxzZP1VWnVPSNjvPNwo5+dgosPS+VLp6oSWwE93N7/WtU3CtWBvHlikfMbkbpaRlzBTen2Hlb5ZIj5LJ0kOzVGBJ0yPXt7lZSDRnNpkcxJWpJ8PljGR1Sj0aCL1wtuHLRmJTL43t7YlyLrLAkqz3t7l9bp3x8RF7Y3+oXvY78XjKkTPr7n4dRjgWRjgKMbU0XcKIy+Izi/+O7RKhT+xsL2vVc/b6td71oYV/dH0znplaLRCN6FK/WY1Rkb8BMVQwyvGJQuyaMyyIy3G2zmKE97VnzaEX9aXZnufURI15Xihsj2bF4kUerpGC2POq73VW+Km2zyitn6w7BT7HCnzkE/Nku77P933zybd4dIrHCUrlbcUquGS8VcbuAu9jCzIsRByFVcWzm0BHaH+LD3vDR6gReagxknvN2qv1XqffbZHGyuviwui2LmXRXZBmf//5y7Gphzt/+BOwNmmyw/6zknfqmf7bBrHcmKrH9+euP069TJnm9ENaTLkGM/XqcMTqsKZALEyv+Tw/Tvd15wf82ePyGSwbDMLUZLqBjNpD32bILcxogI66WY+QTFFXkWFRaion1uT2bDpTG/0CSMexDX2p2vZNabO8QXM1/WzdKKlkdGTHF+CHs2GIBT1Kh73tsvBidlgeV+PEnh8biqnv7frTH2rYhDqE3supWWyQlutW6Y+8TJhYWxt8I0/FYo/pNtoq9jwfoCQZdelzj9aEk5abD6Nz9GGRVlNGE4KBU8+m6YWeGU138e9RjLUbR5mM6rlARRapa6vvFkeepFCTOK/G58M+ziRreg+7Zv6lKFnypd1oKKj28k41pR/5xrIH2KJ26yFq18XpjxjYX/6WhxkNon9KH5Cqq5q1d+sNzrfwvnQmNmkpniV4ybZENVQz0Ebab/t0D4JxAhnUy0J57siHA5WH5xU6D9jHLyGCe3DHLfMoL6qLe6xaCi0GSZm5Bkr3VA7SZnUNY1l2qk0KE/kjxStFoR4I6yTtM4TRo1pKRAhMCQ+oS61YeV5nEaHdAJl8RLTqedWNRi2N1iPkMuybQbABinxadbhhjYMnu+UEeVKrjB3EdPrJSF1cGybjYide+klz1rYdlA2NepE3Y3uv1pYYnGbZwnHogFOpc3ffwqpt1XKL7EYQedvYqs91xO4KTz8V0iuR+2Lvsd6Cg7HvtwfA586rvtIuSrOixLYDSsEMVRcYPHW3WD8e7fePc9kXOpwuoAtttr0lV2psalr4c6O8iZCYTzniGIyPPESlfn6h1aUMhP17CN2oZ55ddwdQWs03oO7ghL4B715hfjnNIJaUkRojrbYQtFct1t9iSYggCD2iuJcbB48KbnpsBkVYHgsVLzA8nz5fqoMOvJU34Efzur13fDwZvnr/Gt7b8VepR343XNVNkcS0ahSCup2B5r5j8T9YHztlmb+UvicmGN72dlx13+z7IUT6nmPpuC4HQJbow4s65i5L+9JzrZAVx/ke6PsMunj17rSUlta/GzuuO3YcJgNKlROQ6tyXmfF5rcqnrXaX6DSyuldP69jU9A4E1uf2HZyFNgvY7uDUyxM8xEnrrSm63ydgPWKXR8+/mJ8Xpb2CVjbZjF5ca/rpiI1j1VPh6jPtmx/SYo2bVlD/hj3/iH2mPJutkqVEvju5x1WaFDDrVmUcZyQjUd6sev/vAwuWVA2+jzKkRLBK1uGqdypR1NarkcmDC8NN1bA7F+TvaJBP92GVxWU5NMBiEey0Vp2mtWIo9tsD2GG177wasTDG9AbKwxfgBrESx+moMVc44qhAG4nByMzoJvR3u5GkxV7+OH+D7alI3TlGWm/fAEUON5UKfybg+BG4FxlnvVZDsxRbESDsDc96Q2ZaaT6Gt4F+ixTKn3krIu+dnh675a199z08A0aNu50BtqSGPZRgSbhxsmK2kZYMqNaJsbMABjGsaWHcXPy/jeBUZAUcipKNmTalQN+uTwANkywuZBjLtWGyLhqW34XJrF8p88owtNE///WI6OHmEVJ2Xo68Kkn7VC3YCHwctnFSDh2XVeGkUZoWo78bHXQ9Gtz1dgGKBkpNSyMOrLcpbMnfYfT3yKfokBUOZm4/LV9lxp6/76NaFZrJFjuMUPMNOGuu3eqM8CxNHVweBl50JpapdwA8ae51w7LMDGRh+lzC++3H+59Gv2xGfMhoxxXbbP7ZQHOrnUHvzjbDe8H+BMECPooH3YE+m+6m3r9Fzz5I1WKZSMWwFKVt+mR2JlgCAz7YDnwofoQHEWE6KRbm3ZkFMtBSwbRQdTxOC85xXUswke8Pf75O6+Fs5s2UGraIVOou03Gt+wYIxOPgcVRnY3iWal1iGxfpvWeHg6dolC97nOepl5kNwLfOq9FS9dJ0717tTMWZV0SoZ6mPjYkeJw0LpPHGxBBBTtS4GjUPPduv2AQaXbte7e5gAQNCeN1imRE34JL01d5o6LEtjugBHZe7ZDWIaHEQEcY+p8c+6xDt01weCxYPeEtwYH4oxB4uPxlzOYeN6alxzMUlfWl/rzxoz/JJxkzOKhiKV6xrWGuReDwsNqE7BzJhKM6W6JyyNx4OAnR/65uPHVZxtsNg3psHsWkuWS3zNeWxluFhhiFI020MdpsCphw3uL81UIZYhmvFFdmcmm4cNgiSTq4nE7UW+W7JH9cBerMW2gXRxn5g1Fa2lvfi5doNCg7sq1KnMKj5R1TvNVZpw3ZwEHoijjyFqz2/NQHTootsIbrIUG93YV6SGn7CYO+SMScyxhzqYqfpW+X903fhlj+PNRy0jxqTcv455bkHcVdMiANd0jdMiATYzNJyD2z7am8kQLXeS3c43GUkshl+YOTxvT7IUgYTzOkgne6dq7JZeFCUp5HqDX/gGAbaKMyC9LRAAlH5aCLT9vJjQz9pxuUU5K3qSdJi9TuMkm3jqg6Npwy/w7KJBjK+g4S0jfkBJvesMjDGY6O9NL5BFdWfHEJ2q3yHtNYMGvePvepMLg7B1uKD0awyd05EGco5eYfWgvsufG5xyAAzNn2GuLpNL+/ERnE2wneP4bthUNogbXP8yWoSwGs2t31eDoCCevMS+uD2VSmgeZ9ouPfRAPjL0mzdN91f3k1oWoQhBE9JnnbTszYs0f7ozpFDuoBPHTogocKKp/0iakY3S+2bw0EakeJxiCOOQWhxqS9DMjkWh2Xu0ie3dPBN+6PWFcdXtGg0q4CNZkWj0qytX+22GsOo6t6DNj02F0qrAaawp4WuXQw6qndakzCgXgFcFFqz4Ndq4W/v6/MMyxMV1Oc5JZ+lhuomCWLjOoIZxJzwvDOT+boo/ZvZ4JwzWFT0yvW0t7IoaGmdEyBuTB/DdEI2PVevBcVpvVuscevJOVQ24JhFHeJIxF41PXvd4f193od19gXkUgFx/qxEjEvyFjDPS3SWFQF0QVeMuI7OTXPSIFKp6yE0MSJXgs8KiFUstOBNJ4msMcyIH/dofui9hhcd0ABeM4wo8gn5yfHAjBCqAFwJvwExQLtFbf5ttaTOnsgYLaq1TFPCsHFexOklICr/pgLrWGP8rPgkAIFB1Rgf+wZixnfOcU5EZEtwOFoIkFm27E85NDssAReo4DgJ8ui0vr7Vbg1lxbYx78/WPLoJLvSc2riMeFzNXuuYHx15zbJMhW0Gg9NzQRoWfZH3tQ3b6uqe8aImYhQNRtpmAdHOSCF5McUgoP5yOd7TcYrokMGrik8bG5HvDnMRsOxEXHFAq32bowFeq+nZeV69ai4eJx6suDMZi+pwXJvGDnnE5BRjLIYWR9quW0Wdyt4pSctnINDLL0voqsGZJYI5I62tARrI2yaGpHsZGP+z33pseBgjTNOatJjuFhQ281hitlJADdSZUtPaSM6QZcfYd0ChbhxKkcxHJc1jQrpgfrHI/KJpp/BtOPE0bmD8cseun+P0oUcvFRsRpfXem2rn6ANqk/qgsbvw2ifRb6z3zbgHgUyMvTVBodrp6fnbG+1th02KNcMo1ojGIkyrfzqB4dDXswOlvw3dhxIIU12W7/k+37oxb9mcuiU3kA32M/W09Gdi/gDcf6w0PHgh/TPUOAlK2hfgiCX7i2XwSp10n+Aq7t1O68J4GJbnBit4WeAqdlB3aZZP/9gCryVXcRyocH121RP1Bbl/8d9f0xkU445zjCcqoUZ5K8GEsfTzHik2LGWSRknLtXz/lpjiYr97XH2noN+LFcFmfZoau2/4Jt7wTRRS63i9+tdAVllqcGxy2cGGmcyyybx1oQFB0KM4UjvrLKajEdq+y3e9o6Lwq/A3BuK2NvIGJ0B8LwFrKBpoKrms+kdaYcpZmm/ufQ/hKwjdT1JCFF7QOcobICfkXvroWP5Ig5Fxso2o5/sGpIfi4hEzAo4u5csV3+dt1m2qCpHnEdQccIDIIIPiJgdhQ5MoJIrPvmcD1bNPu/LMu/YIj8RQ54CH11yyZMTESju9gPNz3Rkw6CIagKDXKlqg03fWXZt/zxQ0YwMxzTOqT3jWppu7/nTb9rlB3AwwLPib4+yz5BYM20NRlgZuEBqhlgQpfNcY6mUjzdZC1VYfwPAh+nNggVoM1ky2OQfww2ZGejn4GeflqBU6eSsRkb1ZH3euDyQHhYaIWhkm6evfsBjj5PWGzIbR0pB5qZE8u0EC+Nri0VuVHVsPCjnAebA0Gu5rYp3e09DY0yDUA467d8OPKD479T+Ay0ICmnvFD6grEsctJx+p95WGs6yopCDtS6qqpUNuUBwTGBQnUiXCTq+V9TiXFeBIW/1wxBpQwqxOmy96kEvmYuqg9OhjzDZon6R57iA3MsuENf12OUY0pqfH83VrqBsTSxtUFwWp1oO0ztRM9t5qROitOTwafaxWTzdoAIIdqEnjBUH2jgxQE5WmpT+/q36Gr1fHamQgssfGUdSs4S6SGuMPS+MZx+uiAXZOxDy3O/Bu55qE6Iqsu9ZQtLTMh9Lf93wTU+5p9HujKJ7ffEubE3VioEtzVgkdOvC00u/F6w/rLRKS199pZLUeIaNEVseOp9XhjbJl0u06nWv9gLMtbdCR6ExrxAOEjfMv0xh5fXjfx8NqLQU9glaSbmOnuBeR9VDbDEwnOidpnpUMluQswPGuo+/ky5WAyEvLItfeY9pPSHNWNRSASndam234eYs7YCTsvBrfqnnz9Ov92HG5GbmLqels2BFC1KhrUG4PPCBWCgbGL10K0nJ1A/2Rl6lBHCfTSQpgGacJa0vUh2DDd3fJXxoNpfrlj7GbOhvjpFnRg985rzWDJUB13Ejj55kxiuMbTXJl2bcJc6L80a3EQe+epwlh1raH7bXpbOQNaip/U3WTsHYm4nFeDVLPOBlnI7Tfy89d1SOytC3p/O6wDyd4k1WAc8kK6L2yLrN2F2oy9yFwPaxjV/CpfjEOtHWFf2V5A86dtOe8Ao5Xxt6Jq0Rwk/11U2UCWyom61eKw8TQppKVd2DJ9pJPMSDNi00RiHgt69ng8reduTysA/O7SlNWxjalb6X9Ox2KOXNylmVONH6qWJVGD42jLW/QKfEQWYnIDX6Sehlcb4B9NApiHbk1FPV4Z0L7h9QMvXcAb7RdjuB6sn9DgjPDlgPf55RMImdzM3x+SGPNN6qd9qWArL84BmqpuOnBxXjbW/aU0FnFVUMqU+Cr1fVq95e5GMaDxlvIUMfXge0RGPIbAfXelAgsR5kSITZSzd8jTPuNXGBjvTU7rksRj4ZCDethAYXl+zSMV/GswQTS5oDTw/zAC1OHf43fgkZHUAhOZpVTfTFr9ViWyXsmy0RzovzwiFOLYvErHANwHB6MxkQNK2Qjf+DgP175daZ5bDNW81D0ySC332NyQt2guKCu1i7HnHiaXsdCX9mckSRQq+ojYqXqRmaeBspWW3ovPdNDaFUyfePXefws7YvS+2pkWSVsHkbifOGf1CiGrfFPtgsyjvcZXzD5a6VZUZtdkqSw+KVejYpDeLPYGyMQLfhCnt/Cc0o+nfUJaD3uUdWeiWwOpQhNwAoelOYrtcp11FimK4AizJRRDlCxDvIWHLq1nD33eHIoSgSitMsnZ5aQB09glmx7Va2O/1lpGZG4a8baAkdkvH0+v6iUzIsAWQahay6jwn9FPfegAsql+GlVWhC9Xpa63KHndvoEECXirE3TstTMay9qsW02ialB4ByLzvnS/BKGYBtxLZxythbDB7+sloY5wnf5yUfGP1a6YSRAykLcingQR+hGeddqpA7psMdKG+SlddE3eUiFpJE6xzuHLQ5l5L2EKPkeMi+gJqm1RLRlQ7y+wYZ7bO0ZmFo4DmkFys/hep3u9DGlcLhh6phAAcf2D7EGjnXZoIUPAryRQTzJ8IUfJaoHWZLD8TCvMrD/GAYlMnrqztx0OX1E3o8y2U3UMIa5X3MB4N5FKCSs86LGI8dxEi3hQ/yAbviBCGjO83L8FLZEVG7ru2dD3Uxh/tEuB3O2kuaZpvpSViQxxj0N4DzL/YOR1c2VZyt5B8RfA4BSP6l4+dR7HGyCdBcptcpgJ6HPWCm/dvr2Qam29QodkIGFDm2rFTcnjZ9bdFGebQAI4xiNrSO7ZrILWiIbNSrLCCcLri1TFGmSNF6Pwe18zw3Njwr5UZBK8nahsRs8nyJP1b2qcWLdWIRqlTQuO2NLNiDTxzjOLK8c45Rkz2+THR87TSU99MmbsyEiXhPSm8d/xtPom8wckBoEA2yT8ytgIxJLeb/E1Et8RBp67pKh9r5spnZqAPA0RfDNEreknr7T2ya8mHYds90n9lL3hS8uQLMVGQjdbckfZMQ0GSJKwxpWyGG4IPz1kwOwR0oDU4bTE9fF2ISamLPiEDGkPGmZxpdkpf2upvhIsrYrugQkj4vgDzSrWRuqh7+X9RSRcWacYwZH9g3LRHD171GpnFwmvTRwG9gEbWarphswlbE1sXVEzgp7uAMDxNbT3ll0gnjBU6GooR+Tb7XgzqIazqm3EevZ3r1qelS6pN5jtCZJ29W7PCCiDqhPUOYBMwE6GZSFrG/wJHR9ckT5nJeDJjffPvkaTc9YU86r4drjre0VRzmjKKdB9+mBBSnxaoz+eJNsnMZmosrXrDJrQGq+h3YrtSVYjCLDAQUCLy03cPuW0Hwv91hy5/ok0B72w739Z/xA3uB5V45SKhEyKA6y+G0INrCK73k1SoTT0tP3+Z52PvOY7sj4KEzX85PWgtKWTpxpRVgN7R7id62OdnqjjFH3zbhYL5tA7cFGpBqy04s8D4etp+5ynKCGq0sCD+Kf01PXQxTqju+/n9EMJwxPSqGfDRUiy4JF4OzbglC02R+D5HpEQss3yFBCuo1DZUe2V0lOXL6lXS0yojgpH+wgHBKyDccEfHK8+ogEeLvTqI6NLZU5i2iIESVJ6yLi2tHb1tCLUQl4Ow3DJ58PX3Kjp9C7jg2HvnW7HHvfvFmlAcZ96wgipkhGRZi1UgzmZJIscW6UCnVAhTiQXGTAeZNkMLRRwtDIMlyKAUQDnJ00zitgG/1TTpDgNELxOQoUSPE2yQAmjVHFJN20Qyl7e71Q49jeHA02bDQYko5opf12co8fs2pdAROGTb2vX7tt06NPzZoNgJJBgUeggtQ8YE9zwP4eMpuxa1AWhHhNOKbKcMWpBWhAQ+sn0Wg6sppZYKbY9cBdJQsK1d6C1o8Gcopmf8WDe6WHYphqIaS82Opo9tvptMaY2rkmmDWqoAHY3yIbxV6bpp/bnBHPd1RyPf7Um4df0+E2pkCA3xWIGXVnAU7ZTLNK6SOuOiaaWkjZPMiiOLyPmcYZ78dnAHJ+Xg03qaRZRvx4x4ibO9GTarsFPntt7592g9EzjtGZun00CoEDWqiZF2fdWqs3MnEKDyOvRtrm41xLVjePHK2lA0HIXj89d9uH/blX4Wnp40H0a1TuUNCaprM9Yqe59435Zc+kqIrGE7VPlJ3MMwD+1kQtRNfOOaAzwLF3OzNIPBM2IcnueqOyTKS8lrW8UTvunkHaI2vPRA94fNQ4brdY8RBNcVN6QfaUu9JdHeyaXvM7PcR58h2BVVoBVBZrms3que+fCst0dqPkuOiShaBg+gGcQvyxLo/SUC50UCJXMOmML2KDN/DsTNgBi6gDghHYQzG26e+BCclt+n7bFgwiB3dyDA/iKX35I3qCsszEQydtaoGsKS31QTU1vfcaXO5wWXQ2LsCPpyMqieSRFPumZ/z1hpSyeyFLkUqmT6fUNqiT9iVO8tleOo5gnMsojT/K0I1L8m5c1O6mNl+0eLGm7Tter3qLaZUEQfW9Z+1ssZE9eYQpHsR52Qvij/sHhwpo5c8lohXu5pycaloIOdmEEgMYfitptvmH8VbfFIi6xEDGViWM3cc0L3T1/GvmuVHTgizNqdDbzzXEZ4sMGOZnYril0BLE50rI+jjdhLnpjUgZy8PnVY/x+f7mZf69CTUb2IQakX7hYGCzzWtEy56ZYbuFJHAdD0v8hX7W3oQNjN2fV6ND4aYblLDq+w4rz0XkYuy+uDJrT3cSw3Ybkw3K42SDAmr6yThvte6CX2CIMjFR9DS9iE5R3yo6a1Fx7IsqmGFF1ZFhm1PebZXpYHDVBAMj28qw74qX0Dfo7xEPV3c+Zc48+ZRyQw/LRIwsrV2OYoiRN2LYo51+FGtHkeXoLi0/gxn0EiYSJmtXtTKGf55eAqJY3/cvG1U3YsrLtAnldFbaZeKMdyLib/DeteTC9mScJaq2iPxRd9Acvh7iDe54Yl/2G5HPiYU18TGqAW6s3mZ6/rraeyWjTncFJGzmiPJJoVdUpEBvZytdNK3fyjgqo4bZOz09/unPtmf77OnPPOBrzBHuEI+OSKjjBDa4C0MsNgXKQjlylPpy4a9ZwGTPLuPjGpznQ20Z9rjPfGRirQzqlFgV7vfLItzzTMQL4j1nkzS8zTaqW1stIadC6CN3ldJ82iZcgWyF8NJsSUJh6Qf2GbbHL7oAG1oYTLKqXQ6WNCvtNyTsul0cmTyYS0h6y4OxNBWKtqJIxaLIAS830UjjZ5ZExb/10LBBuoAcsKWgwrTm26MOphlnRKxBdZ9bnWKS1kFdd88jJkZ4GYkpat4tMohZQSQSIiSoysHjxtHs6pHdwyJ0YDVocC/2zePvjd5NgYCLnOeK6K/z9BI4k9xyMBlGBmLqCIEa5jHLNMmyU0f3Ywq/qW8RX5G2k91avCSXvpLFQzkc6L8i9UEzfPaPW41pr3WfcdbpvBoj+O56QXp8upqGw46RgRKoyWF6cAZ1eahUnXve0YZZA1TiRCSTL6iu1si6hImNLbpBNKsRtbTPCnBP9r1HOb7zqu96E65fBemgrVROEm5QXSDg1G5XET/fOhqN3Ka7NC4mMhoXOgtR8r7Z72X1LY6bJt8IyM+C5CNqVlbJ1Wqqtm6QpXG65ozi4ZbFZFo9G+UyQ166yWUS8Q9rJ2klQQ4bjbDMlGA4kSeLsYn3p8enG7QoiJ+OMHaq48Xr5NQWO3TBjP7OAxexSdPCcP3qRTSZGYlnR/NVbYN8uc97yLQ7ilCeH+tMWrMdoqfx3scqgkB3Ey0jXWLxWb1VC6G2C4mNDhCIfc+rkdlMd2hf0/WwsmDwZPQZCXTJDCsy6dEOfxgh2DZojpABe7wNEBlN0w8QznLNTcwUCoAQyLCmeI0Vz8W5p5mdeROBl6ZMzEQg8jTyDkLf427ELb8MVHBthJNK8fU3D/RtBHltQMrNaEEvS7PEW5sZdLNQXfSIu/Gdfrsiqu31wnefcM/WZdXgaz5bIP2dVkD16qHf75fOow51IBXBlXmlpe0+/PDLDQa3cXoHxzi9iWEMedEs8lLtBpVMsO0ImMCXuShNcwadxcS1Z8Vy1RloamqZpeUWim2hWLvUCVZTy+8gzQMlzfPB6K1R9BRRZV0BihIVJ2xnvDonwq5l53kJ0g88om8jeETRrlj5RI95pLdntaxuWmR4VBYYmXnxWlupq7aaoTIw4V7IMihdYtmBdt/XWylMN7RdzquRjyl5A8kAtpw1VRDyll1OlXefpXE2qflYZdIaJjMJJ4Y28k7NA2x8UQ0e5+lnFDVjTdMJ069YjN/JUOM465BS3ReUIoFJphewCyaxgmIAAOGs5jY/8opt+4jnALBWZGyo1GH09E5/RpmcZXyHwhvBvEh1zvo3e31rIr9pnnoEUufeRaxhqX2zRbZUJr1nKpOkaKe4R/RT8XSDiiqyQNGq3CO6urUn+5wFaR++q1s/ntjWeA1fe6GrtJXSwRmXM4AELSuKEZNbPynWfgUVrRXuQRekZUFYcj9pZ4ZMUz/0AdHMUHDaz1DVRVzrGJmgMyjXyBqEaLsdFLdnm2MPXTmbaJOwRknFQQiCzns2VDPSuRNxQuc9Px9AZmOvwt7FXwNSdZfWoKfhlenRayi0p8bdZTxg7ragGh2l0Qw3jT/gDUO9HHbSnCOGqJa9miwvSHkmDSIGdVIGGJAMD2mBoGz9+XR0DwP30Bc/Gabz5napXWs0JNQ0tEDvYRnEXscJ3bMBNrPIW67L6HEmCAtrDQyus2dUopHJdkQPelgm6TfPv09n00VxwAUUtDotP88PgfCr57YbShiYOHsNcajmIW4ifYpF8NxYqHHUtlBE0zSinQxXmHozu0cSHaH/eFgH1IGRxtvB/6YtM8nXaZSvo6d2DAUPyzH6miv6oIQMq+fVyODYZsnQXV9pHfYpysimKBOMeqg3pveKlvY8iSMq4yWH0kysCaOzjMt3vySmn+pSz1sqKfL0E2pc0Tf51vCXRWkmhYovelp7ziq2IWFgcJjSFlVl+opcluYfILE5WX8RKYaSiA9Aj6oZDLvep6PN3hfsuTZ0hoZkGaGiAV8zvYDe/Wnnx7p4nMYXexYZEgxVpnmH1gBsQ+BIN7q7hJTLBohDLM+maXtukkA0mBzqwJG8dT1H0L7ByvpoQq4GfYkhtT5+b2SUrW+jtN54xZ7q8PkO5AdB5NKGo+ZDfPM7ds7bjn1AMGTBdVK9hFXsjJoyveUgjmH148oKCgx76c3Dr/oPneEKqw75RX0Nq6Xh8+vdrDO6sd6+zbQSy6NikytGT/pnG7gNpgrXLscEjpHmayjcZeHWm7L5mo7fNDTixxyy0XN/fCE6h+mvA+4GwyIDwwXdl0/sXjajFoslMTsGdiAitx2Sr86fBzODXsUO66kHiLl+j1dk13LsLvapZN3rgPTJsHEIILjb9Fz+jB6hPm8znkyKtdaq/RKG3dYCJWVh1khZSEV0myfbZ+1/uz7PBo6URkUNhg8w1E+7nHNkGVhQONtcqIQB9MHgqsZMxeiN/Ze4VisJZNrkpHEpMLnbsvc4uxp7IaMU/+z0A87ctx0VG+Ln1mCDMYO6mZWmORpgA8luLCLZCSZsWaXOmItq67LkDaN7pcFONRI3Pfe5VZoTfF/Z8TMGucxCUTYQpqfmXcVFcpTAcGR66qwkamCe8QE0YshMdyK1TDljCNK+YHTdwDkbxrZ8Xo7RZivtPynUOdyD+shkYLCK+0M7z1PcOdrU5Qx1G10NNFDOAlBiPFy1b83sUUrwRshgFjbDUtwlRlLeNKGYr+7ne81Hs7TOIRfLiIqRKBnjkW5PTbuE43PuQPYGCHhHI6FiltgLdBMQcAuQmXCi2UJtW3NHcjF4t7GzOY/4eTkOiCztc8T0LowjZCaKZknujk1vGrct+NHiKvzoXUYGWDOtvDgyV71npBMnSGOlGzHXz/wE1KzG1eDanKzWT/INw4P0rgEwCUVt0VE2mK+ftn80N4SDro0+5wywXd1Pydpz0tI4zga9hw1EhCmdVwMyzp6XBgTvulgzWQwODNdpetrU8w1OLzK23EZ1xSO5plMemEwsm5cyFxo5SyxeRunMvkdqszNJ0ycL5hYyXbdxZM+mSzXMGug0PXqfCGqLfw9ctgpA9VnRAJMx/vLBl6MXZkpWg+t1sjrSYaXdFmSuo+5OBA/v0QLcQcSvIHa/yZAkOEEz8oOZM17pX5GaXiuPNZdjvZGRVFkH5DRWMb8yZsf2sPUX8+UWqcIc/AwVpzt1Arj3cxkTe53C7D71slONmpU0X/fQBo1vL3Kg/qRmgj88wYIu14acUCcfMrzskWkKJjLrcQ+j0IvzqFXqkMHLTlYFDcjjVxux3FTKoYB2zfJm3CtvsMoYLK4cW1bRV5yk8VM39r0G3cSP55lUsgI2frFOFy2jLXamaDk7UyYEQ7DyBiweWAUawGJvAgwK8W4UULTtsJ7bViUGNpzoUmdOqpHXtCxV+agXoHegC0B4mpH9VTEQgEmSV2HhlC2rKjjftaMrPnSyLKne1iiXPDqAxP/R7fMKZRKAjsUAuGcjk0P0p0Zhk92zNPk9ExiGU4UVyUsawuDuPk0hwn0BAKAddXNidc7lfPkbNlyAaVw0AKNzKWBlmEe/ec5k7ig+Io5iFeYQEBvnWzG3bf5gRtgaVHkvzCeeZIvi9NitgtYAQOsOQkbOiaozZAgsqq+t7xIntqF4GM88rwbYPUxrw4V0bsMyO0TGS1gW4cAzDHZZz+0VuH2m3YSs1zFAFwuCq3G2DVcMUoGl6tSRdgyPYieJ6zW4w3ik80wlU6JSDmua2TGf835E+IJQK2jgHosvaBdPS8I0SfYml6Jnoy4wpWOMNM81LHYV587QCAq41k8bBeX3VpvEvhI4lIjKFWp65HZOjG/noctFrZnzcjTMvLxVQwNcjl5NXD84bQvaHl7H+RfwLuv99D5UFY+wIsDMN1tzPTef96hyNGbYLnQKwopbnu4g9UU3EBgJmWBMdp3XoLjdkOQNcBRwh2TGMZIZaiGyONfq76dSd21ZoFvpk8MOA8tnrN4e5W1FWIZmVKY44+HXzZv1fwdKl8NpWIKtV2Oal5bHNbZQBi3YQtYwmi/TGRrqe9XX5vfAkq4fqIRhTjkS4wYORzjkad3QRewkTpmRONFAFDDuNtMCfL0slbbqt0FeTw2sg9ZPT8/mLza+2qTQYeqgwWM62DQOCHhvStVTfm2ZLgmU1qfFafuxZTIbbd2sWAZmjwyM+piB7UrTH/25Yp9pXS+DaPIAIRlWUx0Qww4GvZsjq3XuAMp7+DiCfzqlp18hYHxLVtismXAGTUlANbzZbm5tQwCzB6Yw7tkuR7oXLhfl/UwTzzmMGnnT6cyc7z6njuuZN+sy4HxrepWIxFkql0rHGMRU0rwoIe6IrMDYRB6cYjVYZUtjL6aQlz7HQWmjJCPEqw6EZY4Rwd7SBszDExHQKSZ7qDibYN7cYq0V1QjFgdv0cDgGSA/CG9PdZa4OKYbQBh4xfopYiQrY6UImhNcVJSoo9xjmh2Hk64GmACQhp3LtIJ/J0rgo6i2rSZm1rYDB0Ctp+l5PbOpEZo72cENvpXovMz/4GVUuqmAtR9Ca5wiUfej8Zr3f12YvhBbg5G6Xg06ZvU//UJ2nURwECCgzq7OZcG/+vgBssUERVC8pVVWFKA23ddmDTXSCMo3JWTQwuYdz5O0O20MUbSjQIBZQKWzdGCuN84ry6tTQrh/TjZFfdaRXTUHYqgeZEW8MfTlGcwlMHqgL7oDlb3j0x8wwAbJYhzq1lkc2YdZOf0y/6DBrcz0ArOMbSt5LkDZsdBc9MhcZkxmVtb3+LU9gyZrx16YAE/LYZWn2axS44LqzEr9hE4Fhkaq82eQTZ3uIFmA09dAVRfwdt96XZEHsmBmxI1UknL9+k29nZCYhPYNyCwYqhtM7bMfTdr9VO+y3OoCXJWm6BpFvv1hJnaChph/7+VHhX+wbuuiTbWhHhgFarR9OGCicWn2bbnCtXibL1uzUKC1hIrM3UZpkTduNurLp6C9FlwOZbqcHrkfShoZxV0Q1iI4pfVoKqKOa15sh0/fGnTKdewVoC8wp9o397V7tkNNSdDleJrNOzbynMgKmqSLxMaIAHDbaTbdqx+uGmkZPnJjijTpRBqMG6qV9IWi49yIco16jVpMx0/NXTPwDfiU+Wh0ikmryosFF2/Zu3ByjSRrxq1PVzM0A1dqbGb/NGlBtNaE712qaNF9qW2BjgnpMKkmzfFprqf2DW1AH3z1BrQtEabuh5J6QkgWGRabZBss2OD35gyAsJxTOyjAKbq8f/EYrRow9DpHec+7RghKtzdOSI4x1qZJY0YJjSaICElrnpk3CIZVLiIzH1FQnC9UGZTAJ0/qCwX9j8MOLCfyEIwMqTHdgzKs7bAoQIYaOBa0z217absC8B7SuhjHpnpcDPRelfR6AbpyqaUzy0GXPx7KV5ls+dqfeKSe4DTHa1c/JvAi0Pa9PCxf3CLXPX+BREKbcLlG+l5K8ASM/uyd3tQ37VyO7QER8PL/Gx6Zphxu6aCQkOVI+Ig5B+Rp3slbVp90Z/jAsZGxhLnEessyaLD/uAdkWA3gNqncahN2Qx6rdaZIXXPazLetnA8bfSdsP6lRtlk/zHhPxQqLAc7POZXc2gmrGkqMzo8mJ08MjSfISs5y4zskRd2WQYJ82zh2FwwS1dIZBLRPwoidpWMBnHxEMjzt1vqYAUz5B3mk1uiqmNA0jKzBagyqRsmyBxhTHlixAR/eh6ngRMyQwZJTGpUzw7lRB5iwRJMWmtZX3QArN75ZUapBXmDhluc7MibYp3OKYcAupsLFCk7YX5DEbpc+OyW6VVfUCOHmW9puiynrEzbMRt/NOATRZLQ+Gaehqj95h4F47CN4TRC+py915MX3BPl2fkCSq4H8TuZts3qz0DnTZNGVDbGI5Gh+u9v2bTb8uybSVRtJJG7HUyVfaXXxQO4G2ZYE2TUuwZkq13vKlnSF514qCCliLQwaufR7Gw/jPfsh3LLzRoHiegZ7P5sn+sncomzVFDxNqVkH1obHa9p/ts9zsobgSl1LIFqaOUF6y3aqeiOPA3TjNI5sw9qgUMi8Uw6fe5dqdZ6xBMRU14vRk9OSOXg6TtE2JoXyGORXUw8Wn3aFWOLHtDJdzhAtdjKDOB7GnpvmgPUat8/xjNX2tSqMfpMS0vEH7pPaDvqjZvCEBdPiGDJNs+BbOEPRfC86QShHaSetc0OchI2UYmuF0Oc6+KG9Vi0tjQ27otjMMOZEXa36AhKlutRSxiJjoWNDIZvFfvGj2byy/RUigSxHUjjVDn2hUbOp7c5dhC1WV4kCqV4ev5D2W1eymR+4RERgyKL7yaD7u8N1cUJthOFwYDYntAsne3SNWtl5TMUCOnHHs3TIEhI4zSPp9xBFZ17lkr8RgzIqnwK21pyvfElgwHxRaZx2gal0oKW1QOyDA05gXLTarzOoxYkBPvoElSF14SzV/TFVDhoOauNIeyxViYKOA4SlNS3QeTgsCec3RtW1KK1Afy0yPf1aZek5wByeyrScfPNdwpYFyHo7li22zrahimKIKVSh5ETFLrNgaDqVADKYQSVFe5tAPmEmkYo8QhBWcC5UEwGdYPcUoyZu2BNBBMeW8GoFqloZxWupu5Dt3rvFOlurH2zRpelwOrF9DT8pqU/RrgwLEqGLxlwEQ/GZF0jWJP4g2UnZABGQYzMKoCQqxwSSnQc7VZg8szPOaV+Pvu5QXavCMJc1CNRgJ9fsbfQKf6aLFuGOOLzcRAxM7k8aW2eWmObw79BCA51kx/2imOZVFU699QohuKWc1oMeNvlz2/g2tWfXSCzlkYNDT+HRp+v77l/ROOTOuWiI4VQwhDfRR+5Ul2xiHEhv4isB9Z+QtevvwnvqqEQOzXMmjdK6ZDPMZ2CUBcUYSz0zxC2uX4xOva6mdkh4npuCk5pnSTL907xU1LkUAYJthZ9wlc9QWJM9nBsmz8OkHeQNEQt4/dnDssQNJlyh7aZV87c7JaaEfnnzvjtVkOkvz7T1uq0zG3pbslEagZqSjtE4B9DpiUVx1U0G5zszPXbOtnYZn1yyH89MGJO2xPKAwF2Ned9IlxrCDmUhTXLh+l+8rarwDnFmuolA3yms/7e7jWNgSOXYnFgYAGdboHrrVA5/ZtpNW6M7YJc4Y4vZmxWggX9okqIk4ruQRjqRZu+F86nJQNoe6bOTHl4FwOSgH89xWTbZZCWqhtuC7uvGJT3FI4sZjN/u8BWMR/qULiApi8Gmxscb9UAgJJdKCwZlXy+rexslO57q9UJCxiWGpaOZVM0SmGfW/Udx9DKZiY3sKhjAVw+DVW50Jb3sZ9+RdIbAWKuWIPIB2e/kK20JpyDL2YIImfrRnBx3oMDwg79dMy8hZBS/AslGFerFBPGLYorTQuTfeK3zQvHvsNROAbyAE46GWowZxZJ2nddK86JWsiAa8xk7PYRE6PdYkab1DZPqu3EHFRaxcJmTZ560kE56lRJ1xwODwroM9o9hAUTXfnv8BqioxTCKyJbAOtiHkcPuM1upUBZ4E/FJBexy14N9TGKWFfYGANgsIPsd5R7Upo5y8QzsBu1fegSUkTI6Y3CyHVhsCsW9m1KZ1BywWp3XoqmnV58wvuPicd7PNMvCAWF0nKt0by5Y+irBjZ2Qps5Elagq4ybIsSj8eUjCRNTuprawZIN/EWd9sVbyPSBSUgE9JhMCAE9+iNe/xAvTyfR8cLX5nti51cd6VkQOBiDvhJvGm8AA4SQKSRQoGojWWOmCG56IAHN4eF9VMHbRdDiejpHmuWLMptAu07gEUpw1rZSId01NaLNu4AyHeLs6Gpr7FR5VEIrmEOCTU3KX5DWunl9r2ylaW0GowMA9RmiUkMGt55SvJoG+DyouxqGYgV1SWHSAXugmPW4SKtwgBpsTG0+q9bkkFZbU3DJmZc7AWRI+zlpbbKfIYAtj7+iGwvj7x82kGwa734l/DUufLQfajy0YidtWLt7GY6Z8c5uAnOj1m1r1+XePL6Q2IVvnDdeoUArq3/GgMHHXi2r0aWGk9ZW6aVEB2QAyvQNxO87JeniamNtDkGnPQhD6aAfjtLARxT+KsOWgJ5CFZtk92HyRvASEW7XLAirS0Lg6s9eaxGgdt/GGfVkXnaVUEGccGmNkh40G7HIRLdmF/j5EjIzzPElVtBRJMS8Twcxs8shbpIArWAjBjyUjrvUFxd1CyePA4BhIVokzCxrZx09Pz7HyHlUN3EaPzcAwvimNZolLNU+65oHulGDbqFzT3yKI/aUS2BstkfK/YjHyh+yBmIROne0jqnJ386gq3VCMfK61z0PRO5DM652c9JwDMAlxkM39iZt42bqdxcFbINQq7iaiMjA+/STLWqCYyQGm1RnwbZG7NPPuYVuUKBM55tOumx/7es1y3mWmIPNvlOKPi9W+4F16XvTkL0f7xugH2Hd3lK+hh4RNlLa/Z/JMKBI2wcfoZLYi73ajS82SY/S/VOg2ar+w7MHPcsNTvhjihQBAJAAfdy2a6kab+soEGMn1oCNNz5QBhoPkrgImN+zH2Gb2uAEGSsChr5tVhRZitES6ktT5etQUkQ5DWmezmLoAMPuTzagzPJGlfwpG3NM61BW5Jg1ivMN3gIetNp8WMjBaTVIiAcMgDndFdiUdgwR0bEnEJhkRwuIivzxJrewSDiTIWb6DLe7Eo1fXfOWdep2YMKYZRobt5y9QFWWPXO5UGojCq4PkYWGSLQRMIT5grY6+mdebKCOrgXtpfU5JP/iB08P1ZYbf9B9R6oJU3EENWWwVHJDI5XiW0IJzT8gYP50UtKu+0y9GAYMvvJJTkCbFOGy/RRMuGffxm/Xy54zvdylAiUsgYBfMxWmV5A8b4sRGRpDFBf25Vjdok3kjzTRHmO+uaGsv67XIoqiV5r1KefcTjFbBEW2jrKFNBSUhcqf0x7xoa4kxXvRzTA+nS/KKsz+Oe0UjUXbiR+Pm1mm7Qa7Pv2ypThq48T9ENTO5N6/OuUSZ7hxmZJJAmjLseaDS1Y3yzygnPHA2o3JpkpH1RJNwCOxW2OnDORPhdK6n6zU/oxfYNCF5E51lngchB5CztT4MQG+4zMfJ/nSJI9WL/v91CiL3sxQrQb4qDh6DyxQZpX2QXW1UMbVgVgwiSNY8FL97yvdpQYGpDgYbVk5N2+bGyl80hxEqPZLHO2EZpX3T6liQKJIhYvQMqPCvNNmboiJFHQxClAKiBrbszp9Qg30r7vEJ+uykH1xmOAxaWReqA6CztL7QiJ2WHEa1VZ5Y7MKUG+FEaZ9HaFie9z1xdWNPOsUGaF05hQQrnBlynDZVHsD2tC++drwlQHSNApVDBhUvLDwipyytVDJfvgaVQ5IXA5bU1NW0ajVIG0IU9/D3hjVDVvN3gjKaeyhHpdrpG7LG6Ph9VuVW8vFOtMlxP7ko+8wR8DRYRTf7qk90TBCGuz/NbQuGIwJYl9sTnEbcXgi4Ltxf0s7h/j3s64MIZlCCTtnypJxBvpjZO3kA4+DVCv0zbo8BeSf+BsdjKG5zf1JZmWB9J8xCaOe1wxNZ6aV8iIvaSOAM1l2g7KKUm/PHNO6DfsBe/QiaRPVJp5mkTcYLqZTkKJpCP/UMsVspPlimwXFLaRaRbzQx8OJktX9NbKtdtRDePs2kqbafx71qybKn6nQjvVvllorTeXmQzvyftB/0YXUoiUH6dnv4c7NzghBqzKHwYBcYi3GS8k6GuiQdASfsILnqWUKwGK61KCOB7uxnnFLTOnaepwk3c5VJsiD6athJAWnM8JeB1XZheYw0wnh5Eto+8Q6VMUbtH8RA1TziODTpSUns5cYcKoUQpSfvN825iuboyWEJmyBT6AHzFhxh5ixN9vJM++VbJBXRnMKgY6nhDJkshnLUQVmK6SQVKQDB15aVxBqi925WGY9A8COHhegBr23fCKhyjrUjYatPByVvxVtvdKHNivCY+QtPdsDim2p1y1o2+rxlNvBoRKIzfw3QHAXFbEP75V2D9I0VsNfbNs+80rHs10cBkQ9YEvVSsxgQvlxZmg6IC5HE10ZfXTDi8efitzqxp4ma0X46NSnVc7ZS0fk6m7cDo4CM6r0YHf14R5FN75CfzYM499S8Umw1yb9amb5kdwBjwiHnoBhoV5v3IJADWPJ8R8U/n1SCswFRej57143HvDtbzyPtlNetMTbeqVcrv7ANH5GnQpD5V48kg79SlDW41COYhbQd5D6kH1Veu51swEP7tW/FN8gvTzSMQhAjTGGl/n2Cz68Eg39J5OaQEp6evX8aoUSwm5co4H9RuEG1l+Jdsvp+SpwMQUY5Z2wzqGJrlPoxirzGF7lQvkYkmD4hUrSlMP+UcD9/qXbkGNVdA33u8chBfM+lypQY10sbwucbSZclsHUXjLLPVZqLb3GDUwgE9ezw8iVGiepbvDHiomfwOYmTZONpZg4rgSxVruOk+n3eTLospyzSYq8/imQYOfM8PMXNxiC1o6j3y1JO4B29gaCtn5ZdCDdiiLZVRmsZleU+1fBZYHrQIYQKqXQ6ax8l4A4JcTFMz5+XZkWJSIrkpZJloRs/EgQKR7yyV9XlDmlXyWd5KVG9WTJVl1gcU4kwCH2/C9EOajObW4SgkDLn213k5EOHh8h2/oc3gcD33Ihh7MJ0XvxK/GmmVs1vcyxAYmpI5Y/IANS3md52s/28oI1dGQZiKTDBBgGrg3fyzMVqPeuxlspgePWZpWzDzbMFSC5MNlLqPdSfFGctQaERK9yz2GNxFDXRIypSa9dRwefZEMcx5ZAfs9haifOoLMlBF/Qt842wf4X0CFiY4jmMPlSQZWkn7C7TSXm0RR3nPy8F9peUdBNZtt1sFdbXMgJl6ukMrqxHCfENJFSu8CsT1WFFN98J9P8SXbPkgUmIV4DIVw2UOu4+D8fMVJ5QLjqWFSjUYL+/Tag4bJU3f4hBsh2Wn+16t2ZGW5qvrHOf5Bp97QO4xB7gKy8OFIPE5C7/sPDpmUOiYzT6Zy57VyD2TxjVAyMKCtEgH2NvZ/mkWVnVHfRYidR/6rs33JM23jb9ojndqcTBsB8t9/aKm5z6pxbfGsvtrRVRa4ekHYS0zPbjI1/fCKtT/SUBfwWF1esjHvJ+B5dVfhZxMRlkic0d+yWaZpyRbk2kQ1ZcAiKzzDB1eaHcLy5ABMAPegsyjDdMrFUC9xUyCY4BjTZhsHqTFiYv0fW+z9UhR48ICtkQb9shpeK4RKqy0AHFQwJgXyIrZa8v7c9h9NgYG6HRHudY7hOs7LBtqbagNRvNKh0oTpJOhCnWSYqMbsZnKGJtpOpKivTT9gHAsj05svVXqrcDab4jSem8yvtvcMpvPDGx5UhyNZH56dsk9utGpLnEelXft8QWRUzF2eqXQc1zXAAMKdp5XIytO0rKAw9yMRqO2jXYQRYpyX56IGPcUL1GePYN5y5cj982yPYvUZa6gwDcaMLXr7aR9jtDaaH/pF0p9hI6Lq+R0WVrnJ/NGzz4hz2M0vc9TG73Ts/M+zwbrthUKDqorMFYsjLl+tQ+kp6gp2yhwFZBhKWn+CRmWxrzVHqdnBm4TKy0jC8OG7hojZS0CenTCuemVCl209bmvEEBlCp0h1VXZYE09mtqaP2bzcW3sDgMkX6p9lJax32LUfPRt7CCNgWlhgSGxWtYvMeopXbBjwn3n5fhsw2S6+rL+jhdQEtsRCE0vWUM91UjLNagbgcaynqrYsKZTkMYohvkaZJVv2bZFzbNrs6txNZDh04usXnJnfMG2Aja44HAS8I36WL7ekhsVZt/asAETu8EuUIyzYIDxg163YTnhmUMnoKMG5VuvJsus5XXLtU+ns3cdk1ERsRhc1E+VqwM8/DhZUhcUSDYo1l+pd3rK4aNP6VYHn3+0QJCPBNPtFnzTLA6nNs9kEax5pEuJyOWjlzcQktLPyg+nphPxvkTgg1ZmWi82s7lsdUWm8ZgRiWNZ+fx8F8sZ61aXCUw9nei33Lw2Ame6gR2CnpMppQeYCWKv1kwQsIfduYTBfLsc0H8vb7VLfmbZQNbhJRwBBdgJTnSWe4o8tnOfQ95UStEgPxqk+eKHewaywb8VsBIWjvyGnt2ybsW5IvzT3fiwSvceMVXHuU2wf8UAT8jHea/11lA3MPOpo+szn3WcQEu71SOMj2jBCMdpZFw2JPHMK8CwKCOuefchtUw1BchU80uTo2Rb3U5yoFvkish+c16Ojp+V5vnhtwGmLE4SJWFKS5Gqa366AWsK3bOWYFNbY1NbsYJpNQv6EmtVAoOEH+Vq1I7c/XqsCrFGM7SFYfMsPNtDts9xKC2D9yP/glwSGL09Q90SSWnf3cv52sDnawlLprg7GQyc6+p9KyFHgyVk2nzZSrtyOVbiYYbVXyt+hlhJ8xvrb2lbZ7o65Vk/I2UK/qdnfwCI102uQuEBoWOhcekb3Dtp/+2hPM/GQLB7eBBMLNy0KAxMtjEyhJzvIUNxVPl0absTh6y9K7CGFO8KJ0LKl6vdH3sZ/nRGQ90gUERg4/xk+rFom8Iius0BE17WvKjhMO/sbKw4MAw4OhlEanHBcPp4sBghSs6BqK5jtTXjp5NzR+AZmAHOq1GHidI4b5Q/ISouHtEg2XKEmSSRsfsrodQlAZjvk/D1ZReafwLdJhYsBsmfsHSUCnapj4A6RGqxZvlmAkT2T+XIGegNG1bxNWGWS17Dy4vIBGbX7kUCjn567rMH1lzwFvYMyKdi1n2mp6rvTA/PBtLvcmCoNZxXg+KUPXEUNYytihGepO6It0A9mgf+3XprqS33R8ZxTRYP8TAxzviAN4GWP5uYSMUYYh9qqu4xScNMnWGRHwKR6Xk12hjsS0mCrX1v6HwIh1YXG1Xnv62qL07aF6wR61HNnBiNVXagR8AJggy0YZ4Qn4GCSiNugxqvkjdA8dm7/CdgychDh8RyJwKTU7uc2E7DVIBLwPaqeCxHJI5bB12HO0UGdyLOtuykcTkd+AzhXdQJM0xOaCBnFhl/hvmGvWHNPmAGvUdnUDma8VyYPEPhN6jJlWbMTEhNPq3VKTrxPbAMFxm1o4sgn+m8vbzRFrts6/x4OO8CZ7vErYq8kQuFnKaYh2yjWiXkWvCTZc6o8XAnecYibiOMixtWb7BUWR5ljD2UHiNVKtIlGvTn1Jt1etbEiryJRVN67LyCn7DHHtmgGoywJoCwhmPtSeC+vJsPa6QUwGGlQQ2N9wpq+fx0RM+h+53hjukjjtWv8d50L8FuuovKCwE5JDzFxqzdX++A0cg9zBsJ+ov4NYk9w64JJzUfm/nbYrMKhrFZkZw5UqAHxrC52RZuDtRGNqFL8lkGisvjBtyB7ig74UeVIwC3sE6Iy7NH3NGyHQi4S+RAx4ufjFMk//8DB1+hPglNmwt+o6UiMNA56E5tXDUXjTT9HmI/1/Fgr5TJZdordn5kKU6/Q5OicYrKF39PAXeWN2in+UOSmsg4agDtE6V99iktka0OWvHWQAiLzL3NMleP2vmKEisxFZhcoJwya3kDrmC8J6QZsftZIivKWnHMtd0BVSg2StdJKGwj2xYEOgH4BEeg877gaZvIRWBjcQm0pNKl6Q2ExYCaITpRRaIw0T5f2l6AcVs72AHI17NAYP5AeUtsT4/GMj0aknRRfLFhROUKXTUPtxoGqKRBBmTHa3ZFsL3RrMqYOIQjNPCgEhGk/brH36prTUVaxSgMzsuRdCtpnFXcd2cwsIVtyxgZ4fHUdAc+u7MuvUNhJsP4hYmTZcZ6uEEIiWdFHtyq9aVatD2qtQ8o63LnHDtTAyjrG6ulcR6/L1lWEhL4JRhlNHkyvZzDuvBY+I1qD01xrZy03w67Sz4Bmdd7z/J6AgdYnaVdVnbc0DQAmRVnDUJCAvtA/fcAZTnrEgjR5yBtM9mZjdXOvWSq6HJ07pW0PukWb0RyCeXizquBTp5uUD+hzZmfTvAGJTJ/XI7nd3y3jJXflfRwgxu6nvyhjzxUivf0Zml6AL2eZ9EZaYRzynA0q5CuX+xDzgLTig7IgWeSAmYkZIfFd9BD9QUcP6FEAGF+NQtbRln5nn99Hn1jZynBhrKR1iW6YU9gODK8XLAFND44jKy8x4l83NQcbLh8pLqyFkmSkHAhcKK6pSZma8HDbON5NZSjw5v1eTAekpkaYylwU4Eshcu3e6/x6NosBISMvlJrDZ4hlgfEOZBZpV6MAEh1uG9NBJQ0zdW5VnwodkjWjGyJ+j/OSeP17HiPd7iQjrQJpXVDn4ystc4gzYsjdQUnLok6YGOKksGopHozrQzSAd4woJvEFLSBtNOxBx7TG3vcYq2saYEsQXXW/DpT6y+N04G0nLDPjHCAiAz4WZTWFR0RzmXeIlSJsE1iiyQRQy9Np0HldJqO0Nh3KUvb5Q12T3tHEmmZNlyAmAXFsAKyTm1J8DXkh2NchTA2juC6AHRcW2OyzfcldH0026OVtPxg1qTTCnjqTvtoUcfVT8vyqIeMUusmAR+FddNzC/riJfbIc2p/IObELwbooNb1lZYAeTa+qjM5bCUt3+tFT5U409POPjpJ8q28ggiPvRPZ9qEh1Igv6BjImnOU5gX0Y1l2ipaVnXKm4uq0LgzstecBIxKOByAttnpaGSGotdQ7ZOQlnqY9WIkC6asGSmjNUSp696XSR2Vhn+QNeMFpJS4UcaivsC4OWGC8XpNVk53H+bqxnTnohbAl0Rd90z1eAsM5+w0J5Sgj78DLTiuINEaBuMVx+KsZxoNhu7QCgAlbyMBp8s7p6Qai8vwAVzOuRvIWpHXGfrwk30N60tjLh5Vb1UvDjVv1iXrZkTtoz1HSdAjFyyd/TpvR+6NY3YoKBth1sPJWrVH0hsfool+BsgnENsR9mN4+6TwvDHdSCAKQ2ze7/aa0xUusGjElCSezTJi2DAMzbRRws0Iqy6xgZhAZY5p1Nmh6F4aPSgUr5HiMANLkBmqvYmdZmupIhgbLESISglLxl3nV1Voz9XiETceijUM0MU6ab8fGgKivg0Vg5nUZyQJZZU6bjXWRHZzIJpAKDU2ORJbppfkWByyTznYkZY8866BaE4O0jCKAN8X+oF4243gZUXBbH968yV2xXTeYGdqXGgh9nPSbtegf0KOiU2A5cxEzoA9VJXknHqbveAGFTkARpmZ6oUIsaGdwGM7UMjhMRGl+3o6sUPxohQbQrIMGqcIV2G2slCHaYFgFpnufoZvLfYGdRHA3wnbFCunnZXdjrOSq7fRmd5poqY87qHE1fLCR5qsPfqvXIfULFEQzzvfqU9k384Of++Z9LCNZ4kHFpHDTkWljpWmBcVmCBt1gCG0Tw4DWscwlkHbYoq3o2iAr5NGqfUbVe0VplTG7bbE1gfJ5Ljz/ibraWlqHwf67o8i3FiJKYNWWItXL/LQerdbXHPryPXrL2P4VNfymp+Yjh0tKyogopTL1nGBKkj22pz7lFpmebjQEgWsHBrLPulDaixLUQ5qviFFStBkUjQyrKNYbnXj1XdY706aSUc7uuKGiJqCZfsr5hvd5kGs+DRwowE/kkjQusus1n28e5dwmVU3TcS6a69e81nBszDMZQLGlfgkKJsw0dSye7CA3QLe90hgpVuJblE9Q7I2CI9qctmfZNfzACzMt1HLf+DMrg+KGOzYmEZdbN63POuiY0UBA5qadxsFHXmij9b8JsoXUVsYFyjmAQIU1k3U+BXWnjmdZjxel5UQyHCelp42KT8DyiXMG6KeEy4wXJYKNWi8qQ5qyQUfwrqR1seP3Sm0w/3hejbbRtDhSFGSDpIQxP7fLQRY1LQ/Xa9xLb5RIb2h2iJfF4rORAj0LnB0ZjqIoPqvLvXPfBvRtCyKERAOnkGWddVz0LWYCHmIXdl0kgfYBYnlnptURTY6FwhbGCQ5a6i7bNz/hffuEE6J4hjwocx00o+yuX+m+CLDlnQIgxTbSND9XF5NKMAFlR+GklvKZ3XQxpPyYSFZj+KF6+FGHE7y8mUhi99RoQdHHFpUQIg7mnYNEKXiP5lcVt8yESul0tdKu2I1bkGyFkOwA7LQcNVntn8WxR67MWq6x4ygqs9O6MLX0O1SAQborj7SuHAg3yO7eMwGKg08PCXm6HHVgZjpL4MtaM6AqEQKXgGKyRgxXo/PEzrzOc44ICaUtqi4hkasnaV4wc+2ogYBowHk1yrRZWkey+R0CM6TjSEi75Hh5HIa3+he6JBeFeaFS24BKJH78gz1rLMkdxD6PMKNDPKjT4VjVx6iLstuKM7LklZlJ6tCnifS8zfykZfTWqfipkx98b6NUCsAgbXMZjmUE4BnVh4eIV7EtTkxom7rcE0hN8XIhsM5Mr5Wn9EsETMLEWOeI+Dfmt3DxnyC9IhY7bIH2UgzMTiRDcjfbeJgYcTo8YmnfsDoNGX9b7JDtfYXSxEcgZqn/Nllup/bTksHgRsCM/mRoHd9XkPc6z77ui3fi4DCKK32k3oJ8c75cpidpzoCutcY2shrrMNnnTN4b8w4WEvtinGqe4c2L2OY2N2poY517MQPLm2IAIjPJzywarQwfUiYqUALISMvtyaF7vlOTQE78CqwCBsnpFqdreE641xnkrAMGOdDk5LB5pEx7wNVaYJV8UjSQm2OZD72IvbmWJGaIQIMyTXbZmPGGTETBAQBEIhgI0RyD5A2qtDVlZSvJA9SvdERAMp45IDtHOFuqkDA41y4HfMFJ++eM4ooZu0lcGyZxbahqwJ2ZBZncfSmLzLRK81CjKb6MFQ2AYOsBIwgv80UzJPhqmXtal1r632DFhLU+r4aLwVC7LhyTQt8AczElF8OkXDRf8KGzcsMIdjEF4bhEGnXiJuM7LFJ6mh+wgya0Dg4aabXuvY14rxf0cEQG+lgo0twsL5SDxVFhkZy2XY62bZ4W+tzZxAnyvsR5hnUe440jDB7iWbX0M62KFIx6j0jOo5nakOWBipzcrp++mN2eBDA66mg7KVjFWml5h8YB9FZjae7YBs8m/EAlIErjVQltK3bp0MeEQMsCjgeqy+nZ2Qze253YAf2Ui1lCWaEceWBEUfsDMkV3NCILxRFdRFCZDtMdIK5eaUybhPq4tkyvgvackqblAMVyIixhj9LZ0LVr6zdqr17oSJuWxK6GqWsWMpNE/c/gLo0/kyqzrXrqkOMlwAyIy9PqVw+2w3He2QPg3dqC0LMkzsU2TxiOYJflCVQFQ4aKvmWzCSbIQZCl1wWU9eF2VSYBOiUNLysEsqqBgzEBJvwVj9/irBKyEURX9geo44cX8HUpaf8ck9tC/Uxi0GlEuPVnxc5CVA/T6Zc0jtdddoVg2YhPpHIbj84jpzN9X/cJHMxSUAuEgcjTumPcvCMTwshXAa5spWVelLkVzXRsMkuNAYWKYpleZa9+9/BtNVQGI4mnOvaoNDC/AtRXpAWwDmsDE07IGlCzDCVjoHB/O34vb6DHsKkfOILBaKblHer7/M5UsfAWQfm0fsADpjf9linxXXYJeJuABhNNlrZFp3zTxbv2IzyUPV12EEsqRi1Qb8Xre3c9Z8NKbgbyXKP1m1/QIUtL9i7LdR3xYBIFzzSJq9/74YLjAtii10B0yofPqukbULTsu2n4sDAacKyNekW0t0yhDWbQ4G3Z67tQZ3lM+YZEXSfAc/hKK+8lifGWo9xFghlqAVn3Ok+d+1PSfvui+p7ZHSlGSqdkQUTa8ngyz2LhNwSQgUHSrEJEmmIdQzPG3TZh6W1SOSXAGcfOD16nfc2t+ZXy7bEZge+wfEwOlD3ebKFe3dmYiuSVx1RArv/9fwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [order_id = _t, order_date = _t, customer = _t, product = _t, channel = _t, quantity = _t, unit_price = _t, discount = _t, revenue = _t]),
					Typed = Table.TransformColumnTypes(Source, {{"order_id", type text}, {"order_date", type date}, {"customer", type text}, {"product", type text}, {"channel", type text}, {"quantity", Int64.Type}, {"unit_price", Currency.Type}, {"discount", type number}, {"revenue", Currency.Type}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
